import type { Metadata } from "next";
import localFont from "next/font/local";
import { Providers } from "@/components/providers";
import { Header } from "@/components/header";
import { ChatDrawer } from "@/components/chat-drawer";
import "./globals.css";

const euclidCircularB = localFont({
  src: [
    {
      path: './fonts/Euclid Circular B Light.woff2',
      weight: '300',
      style: 'normal',
    },
    {
      path: './fonts/Euclid Circular B Regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/Euclid Circular B Medium.woff2',
      weight: '500',
      style: 'normal',
    },
    {
      path: './fonts/Euclid Circular B SemiBold.woff2',
      weight: '600',
      style: 'normal',
    },
    {
      path: './fonts/Euclid Circular B Bold.woff2',
      weight: '700',
      style: 'normal',
    }
  ],
  variable: '--font-euclid',
  display: 'swap',
});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  display: 'swap',
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={euclidCircularB.variable}>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased font-sans`}>
        <Providers
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Header />
          {children}
          <ChatDrawer />
        </Providers>
      </body>
    </html>
  );
}
